# Generated by Django 4.2.2 on 2023-06-08 22:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dishes',
            fields=[
                ('dish_id', models.AutoField(primary_key=True, serialize=False)),
                ('dish_name', models.CharField(max_length=100)),
                ('dish_price', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('image_id', models.AutoField(primary_key=True, serialize=False)),
                ('image_name', models.CharField(max_length=100)),
                ('image_file', models.ImageField(upload_to='image/')),
            ],
        ),
        migrations.CreateModel(
            name='Shoppingcart',
            fields=[
                ('cart_id', models.AutoField(primary_key=True, serialize=False)),
                ('cart_quantity', models.IntegerField(default=0)),
                ('cart_date_added', models.DateField(null=True)),
                ('dish_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.dishes')),
            ],
        ),
        migrations.AddField(
            model_name='dishes',
            name='image_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.image'),
        ),
        migrations.AddField(
            model_name='dishes',
            name='menu_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.menu'),
        ),
    ]
