# Generated by Django 4.2.2 on 2023-06-09 14:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_dishes_image_shoppingcart_dishes_image_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('admin_id', models.AutoField(primary_key=True, serialize=False)),
                ('admin_name', models.CharField(max_length=50)),
                ('admin_email', models.CharField(max_length=50)),
                ('admin_password', models.CharField(max_length=8)),
            ],
        ),
        migrations.CreateModel(
            name='Foodbuyer',
            fields=[
                ('buyer_id', models.AutoField(primary_key=True, serialize=False)),
                ('buyer_name', models.CharField(max_length=50)),
                ('buyer_location', models.CharField(max_length=50)),
                ('buyer_address', models.CharField(max_length=50)),
                ('buyer_contact', models.CharField(max_length=13)),
                ('buyer_password', models.CharField(max_length=8)),
            ],
        ),
        migrations.CreateModel(
            name='Foodvendor',
            fields=[
                ('vendor_id', models.AutoField(primary_key=True, serialize=False)),
                ('vendor_name', models.CharField(max_length=50)),
                ('vendor_location', models.CharField(max_length=50)),
                ('vendor_contact', models.CharField(max_length=50)),
                ('vendor_password', models.CharField(max_length=8)),
                ('admin_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.admin')),
            ],
        ),
        migrations.AlterField(
            model_name='dishes',
            name='dish_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='image',
            name='image_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='menu',
            name='menu_name',
            field=models.CharField(max_length=50),
        ),
        migrations.CreateModel(
            name='Orderfood',
            fields=[
                ('order_id', models.AutoField(primary_key=True, serialize=False)),
                ('buyer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.foodbuyer')),
                ('dish_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.dishes')),
                ('vendor_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.foodvendor')),
            ],
        ),
        migrations.AddField(
            model_name='foodvendor',
            name='menu_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.menu'),
        ),
    ]
