# Generated by Django 4.2.2 on 2023-06-09 21:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('admin_id', models.AutoField(primary_key=True, serialize=False)),
                ('admin_name', models.CharField(max_length=50)),
                ('admin_email', models.CharField(max_length=50)),
                ('admin_password', models.CharField(max_length=8)),
            ],
        ),
        migrations.CreateModel(
            name='Dishes',
            fields=[
                ('dish_id', models.AutoField(primary_key=True, serialize=False)),
                ('dish_name', models.CharField(max_length=50)),
                ('dish_price', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Foodbuyer',
            fields=[
                ('buyer_id', models.AutoField(primary_key=True, serialize=False)),
                ('buyer_name', models.CharField(max_length=50)),
                ('buyer_location', models.CharField(max_length=50)),
                ('buyer_address', models.CharField(max_length=50)),
                ('buyer_contact', models.CharField(max_length=13)),
                ('buyer_password', models.CharField(max_length=8)),
            ],
        ),
        migrations.CreateModel(
            name='Foodvendor',
            fields=[
                ('vendor_id', models.AutoField(primary_key=True, serialize=False)),
                ('vendor_name', models.CharField(max_length=50)),
                ('vendor_location', models.CharField(max_length=50)),
                ('vendor_contact', models.CharField(max_length=50)),
                ('vendor_password', models.CharField(max_length=8)),
                ('admin_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='foodApp.admin')),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('image_id', models.AutoField(primary_key=True, serialize=False)),
                ('image_name', models.CharField(max_length=50)),
                ('image_file', models.ImageField(upload_to='image/')),
            ],
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('menu_id', models.AutoField(primary_key=True, serialize=False)),
                ('menu_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Shoppingcart',
            fields=[
                ('cart_id', models.AutoField(primary_key=True, serialize=False)),
                ('cart_quantity', models.IntegerField(default=0)),
                ('cart_date_added', models.DateField(null=True)),
                ('dish_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='foodApp.dishes')),
            ],
        ),
        migrations.CreateModel(
            name='Orderfood',
            fields=[
                ('order_id', models.AutoField(primary_key=True, serialize=False)),
                ('buyer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='foodApp.foodbuyer')),
                ('dish_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='foodApp.dishes')),
                ('vendor_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='foodApp.foodvendor')),
            ],
        ),
        migrations.AddField(
            model_name='foodvendor',
            name='menu_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='foodApp.menu'),
        ),
        migrations.AddField(
            model_name='dishes',
            name='image_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='foodApp.image'),
        ),
        migrations.AddField(
            model_name='dishes',
            name='menu_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='foodApp.menu'),
        ),
    ]
